### ISSUE TITLE
SYNTHETIC DATASETS

### ISSUE THREAD

**Issue by lsabrinax** [Royalvice/DocDiff#1]
Thanks a lot for your work! Will you release the synthetic datasets you used in the paper

**Comment by Royalvice** [comment]
Hello, the synthesized datasets consist of foreground masks and background document images. I will publish the synthesis code for watermark masks and the mask images for the seals. As for the background document images, they are partly in-house documents and will not be made public. You can collect document images without watermarks and seals from the publicly available document datasets and create your own dataset using transparency fusion (which is also our synthesis method).

**Comment by Royalvice** [comment]
Upload Already
