### ISSUE TITLE
Inference on variable image size

### ISSUE THREAD

**Issue by zairm21** [Royalvice/DocDiff#11]
Hi,
First off thanks for sharing your work. My question is that does DocDiff work on different document image sizes, e.g: image of an entire document page or it only works on small square patches?

Thanks!

**Comment by Royalvice** [comment]
Thank you for your interest in DocDiff's work. You can refer to Issue #7 for more information. DocDiff can perform inference on images with arbitrary width and height that are divisible by 8 (2**[number of downsampling iterations]).

**Comment by zairm21** [comment]
I padded the image and it worked. Thanks @Royalvice
