### ISSUE TITLE
去印章的预训练模型

### ISSUE THREAD

**Issue by samaritan1998** [Royalvice/DocDiff#12]
Hi,
First off thanks for sharing your work.  请问一下去印章的预训练模型大概多久会share出来？

**Comment by Royalvice** [comment]
这周我会上传一个去除红色印章的模型，因为训练集不太够，所以效果还有待提升

**Comment by samaritan1998** [comment]
水印的模型可不可以也share一下，非常感谢

**Comment by Royalvice** [comment]
已上传
