### ISSUE TITLE
watermark removal

### ISSUE THREAD

**Issue by zairm21** [Royalvice/DocDiff#14]
Hi,
I tested the denoiser model on a watermarked document image(using the demo notebook) and the results show the watermark is not removed:
Left to right: img, init_predict.cpu(), min_max(sampledImgs), and finalImgs

Native:
![native](https://github.com/Royalvice/DocDiff/assets/139498559/e9774229-510a-4b16-9238-9a8ff29a1f61)

Non-native:
![non](https://github.com/Royalvice/DocDiff/assets/139498559/bddacf5b-44eb-43f6-8794-422c39b1cd0d)

Is there a different model for watermark removal task?

**Comment by Royalvice** [comment]
> Hi, I tested the denoiser model on a watermarked document image(using the demo notebook) and the results show the watermark is not removed: Left to right: img, init_predict.cpu(), min_max(sampledImgs), and finalImgs
> 
> Native: ![native](https://user-images.githubusercontent.com/139498559/266469271-e9774229-510a-4b16-9238-9a8ff29a1f61.png)
> 
> Non-native: ![non](https://user-images.githubusercontent.com/139498559/266469302-bddacf5b-44eb-43f6-8794-422c39b1cd0d.png)
> 
> Is there a different model for watermark removal task?

The model in the demo is a deblurring model, which has only been trained on deblurring datasets and is incapable of removing watermarks.

**Comment by zairm21** [comment]
Are you planning to release the watermark removal model?
