### ISSUE TITLE
训练集规模以及学习率

### ISSUE THREAD

**Issue by yrqs** [Royalvice/DocDiff#15]
作者您好，我想问一下训练去印章的时候数据集的规模大概是多少呢？以及学习率和batchsize相关吗？我如果调小batchsize的话，学习率是否需要在conf.yml中手动缩放？谢谢！

**Comment by Royalvice** [comment]
> 作者您好，我想问一下训练去印章的时候数据集的规模大概是多少呢？以及学习率和batchsize相关吗？我如果调小batchsize的话，学习率是否需要在conf.yml中手动缩放？谢谢！

我们最终使用了差不多8000样本量进行训练。学习率和batchsize相关性，我并未做较深研究。以我的实验来看，相关性不强。以训练集中间的可视化和loss结果和验证集结果为辅助判断收敛效果

**Comment by yrqs** [comment]
好的，十分感谢！
