### ISSUE TITLE
图片降噪问题

### ISSUE THREAD

**Issue by leung-yaya** [Royalvice/DocDiff#22]
大佬好，我这边用了这张图片进行降噪，发现好像比之前还模糊的。
原图：
![608_608](https://github.com/Royalvice/DocDiff/assets/22385732/84912462-7998-4bd3-876c-9dca7df4c5e2)
结果：
![Uploading finalImgs.png…]()

**Comment by Royalvice** [comment]
预训练权重吗？

**Comment by leung-yaya** [comment]
是的，用的是预训练权重

**Comment by Royalvice** [comment]
预训练的那个数据集的样本多样性比较小，像这种多种噪声的图像效果不行得自己构建数据集，重新训练

**Comment by Royalvice** [comment]
> 感谢大佬解答

不用客气
