### ISSUE TITLE
关于论文里扩散学习的优化目标问题

### ISSUE THREAD

**Issue by NUAA-XSF** [Royalvice/DocDiff#25]
你好, 很棒的工作!
论文里 $L_{DM}$ 里是去预测 $x_0$, 也就是 $x_{res} $, 而不是去预测噪声. 论文里也解释了为什么怎么做. 但我感觉二者还是等价的,   先前的一些论文的这种 channel-wise concatenation conditioning 也是去预测 噪声的.

**Comment by Royalvice** [comment]
预测噪声的方法，在参数量比较大，T取1000以上效果是可以的。本文预测x_0的办法，T取的是200。文中也写了，直接预测x_0对于 channel-wise concatenation conditioning 可以通过条件进行预测。而不是只能通过x_t进行预测。
