### ISSUE TITLE
尊敬的作者您好！我想请问一下关于去模糊数据集的划分问题

### ISSUE THREAD

**Issue by Tiehr2000** [Royalvice/DocDiff#29]
您好，关于文章中提到的：“We randomly select 30,000 patches for training and 10,000 patches for testing.”，请问数据集具体划分方式能否提供，或者这个随机划分会对恢复的效果有较大影响吗？谢谢！

**Comment by Royalvice** [comment]
划分方式就是对训练样本进行随机划分。对效果没什么影响




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Royalvice/DocDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月25日(星期六) 下午4:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Royalvice/DocDiff] 尊敬的作者您好！我想请问一下关于去模糊数据集的划分问题 (Issue #29)





 
您好，关于文章中提到的：“We randomly select 30,000 patches for training and 10,000 patches for testing.”，请问数据集具体划分方式能否提供，或者这个随机划分会对恢复的效果有较大影响吗？谢谢！

**Comment by Tiehr2000** [comment]
> 划分方式就是对训练样本进行随机划分。对效果没什么影响
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Royalvice/DocDiff" ***@***.***&gt;; 发送时间:&nbsp;2024年5月25日(星期六) 下午4:50 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Royalvice/DocDiff] 尊敬的作者您好！我想请问一下关于去模糊数据集的划分问题 (Issue #29) 您好，关于文章中提到的：“We randomly select 30,000 patches for training and 10,000 patches for testing.”，请问数据集具体划分方式能否提供，或者这个随机划分会对恢复的效果有较大影响吗？谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢回复！
