### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by liuyifan6613** [Royalvice/DocDiff#5]
请问放出来的预训练模型只是去模糊任务的吗？其他的子任务的预训练模型会放出来吗？

**Comment by Royalvice** [comment]
> 请问放出来的预训练模型只是去模糊任务的吗？其他的子任务的预训练模型会放出来吗？

都会陆续放出来，其中文档二值化我会上传HDIBCO2018和DIBCO2019的结果图片

**Comment by liuyifan6613** [comment]
好的，非常感谢！
