### ISSUE TITLE
推理时长？

### ISSUE THREAD

**Issue by samaritan1998** [Royalvice/DocDiff#6]
请问一下推理时长有测过么，和有和Gan对比过嘛？

**Comment by Royalvice** [comment]
可参考原文表5，每推理100万像素图片（包括IO），默认配置下DocDiff(Non-native)-5耗时0.33秒，DocDiff(Non-native)-100耗时5.69秒，MPRNet耗时0.57秒，DE-GAN耗时0.82秒。总体来说，DocDiff-5速度还是很可观的，因为DocDiff的HRR模块只有4M，即使采样5次但是计算时间复杂度也很低。但是DocDiff-100速度还是很慢的。不过，DocDiff在文档图像上的训练十分稳定。如果跑过DE-GAN的官方代码，可以知道GAN方法很难收敛。

**Comment by Royalvice** [comment]
如果您还有什么问题，欢迎联系我。如果您觉得有帮助并给个Star，我竟感激不尽，谢谢！

**Comment by Royalvice** [comment]
> 请问一下推理时长有测过么，和有和Gan对比过嘛？

Demo下有notebook，您可以自己测一测速度

**Comment by Royalvice** [comment]
> 可参考原文表5，每推理100万像素图片（包括IO），默认配置下DocDiff(Non-native)-5耗时0.33秒，DocDiff(Non-native)-100耗时5.69秒，MPRNet耗时0.57秒，DE-GAN耗时0.82秒。总体来说，DocDiff-5速度还是很可观的，因为DocDiff的HRR模块只有4M，即使采样5次但是计算时间复杂度也很低。但是DocDiff-100速度还是很慢的。不过，DocDiff在文档图像上的训练十分稳定。如果跑过DE-GAN的官方代码，可以知道GAN方法很难收敛。

单张3090
