### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zairm21** [Royalvice/DocDiff#9]
Hi 
Thanks for sharing your work. Can you please share its license with us?

Thanks!
@Royalvice

**Comment by Royalvice** [comment]
> Hi Thanks for sharing your work. Can you please share its license with us?
> 
> Thanks! @Royalvice

Thank you for your interest in my work. I'm happy to share the license with you. The project is licensed under the MIT License, which grants you the permission to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software. You can find the full text of the license in the repository.

If you have any further questions or need additional information, please feel free to ask.

Be free to use DocDiff!

Best Regards

**Comment by zairm21** [comment]
Thanks @Royalvice
